Removed code comments, set up project with code checks, put all urls …
newton-crypto/auth0 pull request #1
Opened 2022-02-22 15:17 UTC by patricklnewton

…into pulumi config

2022-02-23 15:07 UTC, inhumantsar requested changes
looks good, just a few readme suggestions

2022-02-23 15:07 UTC, inhumantsar commented on README.md
> +7. Run `pulumi up` and hopefully you have no client grant errors.
I'm confused about these Requirements, this code does step 5 yeah?

And not to move the goalposts, if you agree it can go into a separate PR, but do you think it makes sense to create the Application this Client needs with Pulumi? If it's possible to source the Client ID and Secret from an Application object, it might simplify things a bit.

2022-02-23 15:07 UTC, inhumantsar commented on README.md
> -    bump2version minor
Please put this section back. It's meant to guide people on contributing to the project.

2022-02-23 15:07 UTC, inhumantsar commented on README.md
> -    brew install pulumi
Could you rewrite this section so that someone who has never run a Pulumi project before could run this?

2022-02-23 15:45 UTC, patricklnewton commented on README.md
> +7. Run `pulumi up` and hopefully you have no client grant errors.
yeah that totally makes sense, I'll look into pulling the client Id and secret from an application object like you said.

2022-03-09 15:23 UTC, inhumantsar requested changes
looking good so far. love the tests. couple minor changes in the comments and a couple general comments on structure:

* it probably makes sense to keep the actions files in the google_workspace directory since that's the only module they'll be used by
* if they're in the google_workspace dir, then you can read them in as plaintext rather than having copies of them embedded in python strings
* it might make sense to name this entire part of the project "aws_sso" since it's creating an application which AWS will use and connecting it to an existing google workspace connection
*

2022-03-09 15:23 UTC, inhumantsar commented on auth0_actions/actioncode.js
> +exports.onExecutePostLogin = async (event, api) => {
nit: these two functions should probably have a name which describes their functionality rather than the hook they'll attach to.

2022-03-09 15:23 UTC, inhumantsar commented on google_workspace/.github/workflows/pr-quality.yml
> +name: PR Quality Checks
the `.github` dir can't be in a subdirectory unfortunately. you'll have to put it in the repo root and ensure you're feeding the tests and sonarqube action appropriate paths

2022-03-09 15:23 UTC, inhumantsar commented on google_workspace/__main__.py
> +my_action = auth0.Action("@aws/sso",
should give these vars proper names rather than `my_whatever`

2022-03-09 19:44 UTC, inhumantsar approved these changes

2022-03-09 19:46 UTC, merged